services:
    proxyauth:
        container_name: proxyauth
        build: .
        ports:
            - "8080:8080"
        ulimits:
            nofile:
                soft: 65536
                hard: 65536
